name: veta
channels:
  - bioconda
  - conda-forge
  - anaconda 
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - cyvcf2
  - bcftools
  - scikit-learn
  - imbalanced-learn
  - pip:
      - hgvs
      - fastcluster
      - statannot
      - gplearn
      - sklearn-pandas
      - dtreeviz
