name: veta2
channels:
  - bioconda
  - districtdatalabs
  - conda-forge
  - anaconda 
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - cyvcf2
  - scikit-learn
  - yellowbrick
  - sklearn-contrib-lightning
  - sklearn-contrib-py-earth
  - xgboost
  - imbalanced-learn
  - pip:
    - hgvs
    - git+git://github.com/webermarcolivier/statannot.git#egg=statannot
    - gplearn
    - bleedml
    - sklearn-pandas
    - dtreeviz
