name: veta
channels:
  - bioconda
  - conda-forge
  - anaconda 
dependencies:
  - python==3.10.6
  - pip>=22
  - bcftools=1.16
  - postgresql
  - pip:
      - matplotlib==3.5.1
      - numpy==1.23.5
      - pandas==1.4.2
      - seaborn==0.11.2
      - cyvcf2==0.30.15
      - scikit-learn==1.0.2
      - imbalanced-learn==0.9.0
      - hgvs==1.5.2
      - fastcluster==1.2.6
      - statannotations==0.4.4
      - gplearn==0.4.1
      - sklearn-pandas==2.2.0
      - dtreeviz==1.3.5
