name: veta
channels:
  - bioconda
  - conda-forge
  - anaconda 
dependencies:
  - python>=3.6
  - pip
  - matplotlib>=3.3.3
  - numpy>=1.19.5
  - pandas
  - seaborn>=0.11.1
  - cyvcf2>=0.30.4
  - bcftools
  - scikit-learn>=0.24.0
  - imbalanced-learn>=0.7.0
  - pip:
      - hgvs>=1.5.1
      - fastcluster>=1.1.26
      - statannot>=0.2.3
      - gplearn>=0.4.1
      - sklearn-pandas>=2.0.4
      - dtreeviz>=1.1.3
