name: base
channels:
  - bioconda
  - districtdatalabs
  - conda-forge
  - anaconda 
dependencies:
  - python=3.6
  - pip=19.2.3
  - matplotlib=2.2.4
  - numpy=1.17.2
  - pandas=0.25.1
  - seaborn=0.9.0
  - cyvcf2=0.11.5
  - scikit-learn=0.21.3
  - yellowbrick=1.0.1
  - sklearn-contrib-lightning=0.5.0
  - sklearn-contrib-py-earth=0.1.0
  - xgboost=0.90
  - imbalanced-learn=0.5.0 
  - pip:
    - hgvs==1.3.0
    - git+git://github.com/webermarcolivier/statannot.git#egg=statannot
    - gplearn==0.4.1
    - bleedml==0.0.7
    - sklearn-pandas==1.8.0
    - dtreeviz==0.6
